version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - ./scripts/prisma.sh
      - npm ci
  build:
    commands:
      - npm run speccy:lint
      - npm run build
      - npm run test
      - docker build -t $REPOSITORY_NAME:latest .
      - docker tag $REPOSITORY_NAME:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:latest
  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:latest > imagedefinitions.json
      - npm run prisma:migrate:deploy
      - npm run speccy
artifacts:
  files: imagedefinitions.json
  secondary-artifacts:
    openapi:
      files: openapi.yml
reports:
  clover:
    files:
      - clover.xml
    base-directory: 'jest/coverage'
    discard-paths: false
    file-format: CLOVERXML
  junit:
    files:
      - junit.xml
    base-directory: 'jest/junit/'
    discard-paths: false
    file-format: JUNITXML