version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 186521841143.dkr.ecr.us-east-1.amazonaws.com
      - ./scripts/prisma.sh
      - npm ci
  build:
    commands:
      - npm run build
      - npm run test
      - docker build -t pets-api .
      - docker tag pets-api:latest 186521841143.dkr.ecr.us-east-1.amazonaws.com/pets-api:latest
  post_build:
    commands:
      - docker push 186521841143.dkr.ecr.us-east-1.amazonaws.com/pets-api:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' pets-api 186521841143.dkr.ecr.us-east-1.amazonaws.com/pets-api:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json