version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
      nodejs: 12
  pre_build:
    commands: 
      - aws ecr get-login --region us-east-1 --no-include-email
  build:
    commands:
      - docker build -t pets-api .
      - docker tag pets-api:latest 186521841143.dkr.ecr.us-east-1.amazonaws.com/pets-api:latest
  post_build:
    commands: 
      - docker push 186521841143.dkr.ecr.us-east-1.amazonaws.com/pets-api:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' pets-api 186521841143.dkr.ecr.us-east-1.amazonaws.com/pets-api:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json