version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pets
      POSTGRES_PASSWORD: pets123
      POSTGRES_DB: petsdb
      POSTGRES_SCHEMA: pets
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  localstack:
    container_name: localstack
    image: localstack/localstack-full
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs
    ports:
      - "4566:4566"