version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pets
      POSTGRES_PASSWORD: pets123
      POSTGRES_DB: petsdb
      POSTGRES_SCHEMA: pets
    ports:
      - "5432:5432"
    networks:
      - pets-api-network
networks:
  pets-api-network:
    driver: bridge