version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PetsAPI"
s3_bucket = "pets-api-local-deployment"
s3_prefix = "pets-api"
region = "us-east-1"
profile = "default"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"